[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[profile.ci]
fuzz.runs = 1_000

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
